# Codex CLI Configuration
# This file should be in TOML format, NOT JSON

# Basic Codex settings
version = "1.0.0"
project_type = "nodejs"

# MCP Server configuration for ASB-CLI
[mcp_servers.asb-cli]
command = "node"
args = ["C:\\mcp-servers\\asb-cli\\index.js"]

[mcp_servers.asb-cli.env]
AGENT_NAME = "codex"
PROJECT_KEY = "alice-semantic-bridge"
PROJECT_ROOT = "C:\\xampp\\htdocs\\alice-semantic-bridge"
REDIS_HOST = "localhost"
REDIS_PORT = "6379"
REDIS_DB = "2"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = "5432"
POSTGRES_DB = "asemb"
POSTGRES_USER = "postgres"
NODE_ENV = "development"

# Additional Codex settings
[settings]
auto_save = true
theme = "dark"
tab_size = 2