# Codex CLI Configuration
# Location: ~/.codex/config.toml

[general]
project_root = "C:\\xampp\\htdocs\\alice-semantic-bridge"
default_model = "gpt-4"

[mcp_servers]
# ASB-CLI MCP Server for Redis Shared Memory
[mcp_servers.asb-cli]
command = "node"
args = ["C:\\xampp\\htdocs\\alice-semantic-bridge\\universal-asb-mcp-server.js"]
transport = "stdio"

[mcp_servers.asb-cli.env]
AGENT_NAME = "codex"
PROJECT_KEY = "alice-semantic-bridge"
PROJECT_ROOT = "C:\\xampp\\htdocs\\alice-semantic-bridge"
REDIS_HOST = "localhost"
REDIS_PORT = "6379"
REDIS_DB = "2"

[editor]
default = "vscode"

[logging]
level = "info"
