replicaCount: 3

image:
  repository: ghcr.io/alice-semantic-bridge/asb
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"
  prometheus.io/path: "/metrics"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
  hosts:
    - host: api.asb.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: asb-tls-secret
      hosts:
        - api.asb.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - asb
          topologyKey: kubernetes.io/hostname

postgresql:
  enabled: true
  auth:
    username: asb
    database: asb_production
    existingSecret: ""
  primary:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      limits:
        memory: 1Gi
        cpu: 1000m
      requests:
        memory: 512Mi
        cpu: 500m
  metrics:
    enabled: true

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: ""
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
  metrics:
    enabled: true

n8n:
  enabled: true
  replicaCount: 2
  image:
    repository: n8nio/n8n
    tag: latest
  service:
    type: ClusterIP
    port: 5678
  ingress:
    enabled: true
    host: n8n.asb.example.com
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      memory: 1Gi
      cpu: 1000m
    requests:
      memory: 512Mi
      cpu: 500m

monitoring:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
  grafana:
    enabled: true
    dashboards:
      enabled: true
  alerts:
    enabled: true
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        annotations:
          summary: "High error rate detected"
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, http_request_duration_seconds_bucket) > 1
        for: 5m
        annotations:
          summary: "High response time detected"

backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: 30
  s3:
    enabled: true
    bucket: asb-backups
    region: us-east-1

security:
  networkPolicy:
    enabled: true
  podSecurityPolicy:
    enabled: true
  secrets:
    external: true
    backend: kubernetes
  tls:
    enabled: true
    certManager:
      enabled: true
      issuer: letsencrypt-prod