[[servers]]
name = "asb-cli"
command = "node"
args = ["C:\\xampp\\htdocs\\alice-semantic-bridge\\codex-mcp-server.js"]
transport = "stdio"

[servers.env]
AGENT_NAME = "codex"
PROJECT_KEY = "alice-semantic-bridge"
REDIS_HOST = "localhost"
REDIS_PORT = "6379"
REDIS_DB = "2"
