name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test with coverage
        run: npm run test:coverage

      - name: Enforce coverage thresholds (PR gate)
        if: ${{ github.event_name == 'pull_request' }}
        run: node scripts/check-coverage.js --statements=60 --branches=40

      - name: Start API server
        run: |
          nohup node src/index.js > api.log 2>&1 &
          sleep 3

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright E2E tests
        env:
          BASE_URL: http://localhost:3001
        run: npm run test:e2e -- --reporter=list
